#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: workstation_num
    username: ben
    password: "$6$iX0ONhfIIhzvXySN$twsH1z1Lkn9V5vPfWjudXq.yerxOr77y8stWieDR7JNWTUHHP0/Wu9kAlxEq0VzK.iYTnPtICvC7w7UefmORR1"
  keyboard:
    layout: hu
    variant: ''
    model: pc105
  locale: en_US.UTF-8
  storage:
    layout:
      name: lvm
  network:
    version: 2
    ethernets:
      eth0:
        dhcp4: true
  ssh:
    install-server: true
    allow-pw: true
  apt:
    primary:
      - arches: [default]
        uri: http://archive.ubuntu.com/ubuntu
    sources:
      universe:
        source: "deb http://archive.ubuntu.com/ubuntu noble numbat"
  packages:
    - git
    - curl
    - htop
    - vim
    - vlc
    - qbittorrent
    - gnome-system-monitor
    - net-tools
    - lm-sensors
  late-commands:
  # Download install.sh from GitHub
    - curtin in-target --target=/target -- bash -c "wget -O /tmp/install.sh https://raw.githubusercontent.com/lyonerbeef/autoinstall/master/install.sh"
    - curtin in-target --target=/target -- bash -c "chmod +x /tmp/install.sh"
    - curtin in-target --target=/target -- bash -c "/tmp/install.sh"
